name: Python Script Workflow

on:
  schedule:
    - cron: "0 6,18 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Execute Python script # Run the app.py

        run: python main.py